{% set name = "tierpsy" %}
{% set version = "1.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ver228/tierpsy-tracker/archive/v{{ version }}.tar.gz
  sha256: 78cf8cf9a9ca694cbab6d4bac244567864150d7044be312ccdf0396684f9ce82
  #git_url: https://github.com/ver228/tierpsy-tracker.git

build:
  osx_is_app: True
  number: 2
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - {{ compiler('c') }}
    
  host:
    - python=3.6
    - numpy>=1.16
    - pip
    - setuptools
    - cython

  run:
    - python=3.6
    - keras=2.1.5
    - opencv
    - tensorflow
    - numpy>=1.16
    - matplotlib
    - hdf5
    - pytables
    - pandas
    - pyqt
    - scipy
    - scikit-learn
    - scikit-image
    - statsmodels
    - numba
    - tqdm
    - requests
    - ffmpeg

test:
  imports:
    - tierpsy
    - tierpsy.features.tierpsy_features
    - tierpsy.features.open_worm_analysis_toolbox
  commands:
    - tierpsy_process -h
    - tierpsy_tests -h

app:
  entry: tierpsy_gui
  summary: Tierpsy Tracker Multi-Worm Tracker
  type: desk

about:
  home: https://github.com/ver228/tierpsy-tracker
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Tierpsy Tracker Multi-Worm Tracker
  doc_url: http://ver228.github.io/tierpsy-tracker/
  dev_url: https://github.com/ver228/tierpsy-tracker

extra:
  recipe-maintainers:
    - ver228
