travis:
  secure:
    BINSTAR_TOKEN: a2Vtn5MvnMiz3H/AglwIK58b93EpV91dIN1RneoUvvd/AwOzlIuSTmPaPNvHZBHfMC3YchbgWp/FWaBzYMPcJaCpE9sFE1PFLI4gEvOLB6IeiQdSblEFFsmlJtY0QNiMwt3BH+g1qAjoaSCJ+pRFSKeYLB62FMr3mTClGIJKcGlUUQveJTY84c7zd4QuO6potYUEImzuONrBVDBp26uqaVZb1QOg4q6h62pk9BSf7BqMNpnD3kLFtBqHlt/+hZkGeBn1UGzDM/jdp3/ASnXkZdmMecsfZWaBU+rgYmw3ovpaSdKIOKM9D+TU39Else4g7FkaYZOfUr5eeHAc13qAR6vooZQXqoFOVpd+J18uhpE3QqfnjdKdTVZmBNraoa20tiJZlAeHUz/U6lLStjMsszA9LjRLtVsAOoZ1zTM1SdepPFUhIMmatUQcKf3CTExDEa8Eeae7ncJCa7nmXVXPNvYsNiGoMfvJS4W0gwOjeqB8/UElIuOJe8a+XZAU+chsFUoV1TOnpnblOhOA2/eEOhkk1CrdQQPUD882+VYd/X/GnINc5ATCPOEtg/exgyYtzCmUR/TgkZrXDg4paD8wShcC3/jKd5gwrOMgZu/098FckYz+H1WMWoKAbk4etpfhYoA+8K3nyjSuN9SKNNTozyZn7tzX2UvhW/qy25901rU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
